version: "3"

services:
  auth:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - db:db
      - redis:redis
    environment:
      - MONGO_URL=db:27017
      - REDIS_URL=redis:6379
      - SECURITY_SECRET_WORD=some_secred_word
      - WEB_PORT=8080
  redis:
    image: redis:latest
    ports:
     - "6379:6379"
    expose:
      - "6379"  
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
#    volumes:
#      - "/Users/Pavel/data/db:/data/db"
    expose:
      - "27017"
